[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = false
extra_output = ["metadata", "storageLayout"]
extra_output_files = ["metadata", "storageLayout"]

# CI/CD를 위한 설정
[profile.ci]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = true
extra_output = ["metadata", "storageLayout"]
extra_output_files = ["metadata", "storageLayout"]

# 커버리지 분석을 위한 설정
[profile.coverage]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
optimizer = false
via_ir = true
extra_output = ["metadata", "storageLayout"]
extra_output_files = ["metadata", "storageLayout"]

[rpc_endpoints]
verynetwork = "https://rpc.verynetwork.com"
verynetwork-testnet = "https://testnet-rpc.verynetwork.com"

[etherscan]
verynetwork = { key = "" }
verynetwork-testnet = { key = "" }

# Veryscan is free to use, no API key required 