[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false
extra_output = ["metadata", "storageLayout"]
extra_output_files = ["metadata", "storageLayout"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

# CI/CD를 위한 설정
[profile.ci]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true
extra_output = ["metadata", "storageLayout"]
extra_output_files = ["metadata", "storageLayout"]

# 커버리지 분석을 위한 설정
[profile.coverage]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true
extra_output = ["metadata", "storageLayout"]
extra_output_files = ["metadata", "storageLayout"]

[rpc_endpoints]
verychain = "https://rpc.verylabs.io"

[etherscan]
verychain = { key = "", url = "https://veryscan.io" }
