[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = false
extra_output = ["metadata", "storageLayout"]
extra_output_files = ["metadata", "storageLayout"]

[rpc_endpoints]
verynetwork = "https://rpc.verynetwork.com"
verynetwork-testnet = "https://testnet-rpc.verynetwork.com"

[etherscan]
verynetwork = { key = "" }
verynetwork-testnet = { key = "" }

# Veryscan is free to use, no API key required 